# Generated by Django 5.1.4 on 2024-12-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_rename_categoria_tarefa_prioridade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="criacao",
        ),
        migrations.AddField(
            model_name="tarefa",
            name="data",
            field=models.DateField(default="2024-12-13"),
            preserve_default=False,
        ),
    ]
