# Generated by Django 5.1.4 on 2024-12-13 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0004_alter_tarefa_prioridade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="Geral", max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="prioridade",
            field=models.CharField(
                choices=[("alta", "Alta"), ("média", "Média"), ("baixa", "Baixa")],
                default="média",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="tarefas.categoria",
            ),
        ),
    ]
