# Generated by Django 5.1.4 on 2024-12-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0005_categoria_alter_tarefa_prioridade_tarefa_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="tarefas.categoria",
            ),
        ),
    ]
