# Generated by Django 5.1.4 on 2024-12-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0007_tarefa_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="tarefas.categoria",
            ),
        ),
    ]
